using System;
using System.IO;
using System.Text;

class Test
{
    public static void Main()
    {
        string path = @"./realmlist.wtf";
        string old = @"./realmlist.old";

        try
        {
            Console.WriteLine(" Back up your current Realmlist file before continuing. \n This WILL delete your current file. \n Hit any key to continue . . .");
            Console.ReadKey();
            // Delete .old if it exists.
            if (File.Exists(old))
            {
                File.Delete(old);
            }
            if (File.Exists(path))
            {
                /*Rename the file so
                 the user has another chance
                 before perma-deletion*/
                File.Move("realmlist.wtf", "realmlist.old");
            }
            // Create the file.
            using (FileStream fs = File.Create(path))
            {
                Byte[] info = new UTF8Encoding(true).GetBytes("set realmlist <url> \n \n    // Dalaran logon.dalaran-realmlist.org \n    //Sunwell logon.sunwell.pl \n    // Memories logon.memories-gaming.com \n    // CryptWoW logon.crypt-wow.com \n    \n    //Generated by SolgRLT\n    //Created by MrSolg_");
                // Add some information to the file.
                fs.Write(info, 0, info.Length);
            }

            // Open the stream and read it back.
            using (StreamReader sr = File.OpenText(path))
            {
                string s = "";
                while ((s = sr.ReadLine()) != null)
                {
                    Console.WriteLine(s);
                }
            }
        }

        catch (Exception ex)
        {
            Console.WriteLine(ex.ToString());
            Console.ReadKey();
        }
    }
}